const colorNames = ['green', 'amber', 'indigo', 'rose', 'teal', 'cyan', 'purple', 'orange'];
const dynamicClasses = colorNames.flatMap((color) => [
  `border-${color}-400`,
  `hover:border-${color}-400`,
  `dark:hover:border-${color}-400`,
  `text-${color}-500`,
  `text-${color}-600`,
  `hover:text-${color}-600`,
  `group-hover:text-${color}-600`,
  `bg-${color}-100`,
  `bg-${color}-200`,
  `bg-${color}-500`,
  `dark:bg-${color}-900/20`,
  `dark:bg-${color}-900/30`,
]);

module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './components/**/*.{ts,tsx}',
    './services/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
    './types.ts',
  ],
  safelist: [
    ...dynamicClasses,
    'bg-blue-100/90',
    'bg-blue-500/15',
    'bg-white/55',
    'bg-white/60',
    'bg-white/65',
    'bg-white/70',
    'bg-white/80',
    'bg-white/85',
    'bg-slate-800/50',
    'bg-slate-800/60',
    'bg-slate-900/95',
    'bg-slate-900/50',
    'dark:bg-slate-700/85',
    'dark:bg-slate-800/60',
    'dark:bg-slate-900/95',
    'dark:bg-blue-500/15',
    'dark:border-blue-400/40',
    'dark:border-slate-700/70',
    'dark:text-blue-300',
    'dark:text-slate-200',
    'dark:text-slate-300',
    'dark:text-slate-400',
    'dark:text-slate-500',
    'hover:bg-white/80',
    'hover:bg-white/85',
    'hover:bg-slate-100',
    'hover:bg-slate-700',
    'hover:text-red-600',
    'hover:text-red-400',
    'group-hover:rotate-0',
    'group-hover:rotate-12',
    'group-hover:scale-110',
    'group-hover:text-blue-600',
    'group-hover:text-cyan-600',
    'group-hover:text-emerald-600',
    'group-hover:text-green-600',
    'group-hover:text-indigo-600',
    'group-hover:text-orange-600',
    'group-hover:text-purple-600',
    'group-hover:text-rose-600',
    'group-hover:text-teal-600',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3b82f6',
        secondary: '#2563eb',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        spaceGrotesk: ['Space Grotesk', 'sans-serif'],
        orbitron: ['Orbitron', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
